root: true
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - eslint:recommended
  - prettier
reportUnusedDisableDirectives: true
rules:
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
      ignoreRestSiblings: true
