printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
arrowParens: always
proseWrap: preserve
endOfLine: lf
embeddedLanguageFormatting: auto
plugins:
  - prettier-plugin-sql
  - prettier-plugin-sh
